export const GET_RESULT_LIST = ["GET_RESULT_LIST_LOADING", "GET_RESULT_LIST_SUCCESS", "GET_RESULT_LIST_FAIL"];


export const GET_NUMBER_OF_VISITORS = "GET_NUMBER_OF_VISITORS";
export const COMPETE_POKER = "COMPETE_POKER";
export const RESET_POKER = "RESET_POKER";